<?
	// ----------------------------------------- settings
//	define("DEBUG_LOG", TRUE);
	define("DEBUG_LOG", FALSE);

	// ----------------------------------------- constants
	define("STATE_TODO", 0);
	define("STATE_DOING", 1);
	define("STATE_DONE", 2);
	define("HEAD", "head_0");
	define("BASE_DIR" , "../log");
	define("PREFIX", "uniqueID_");
	define("SUFFIX", ".txt");
	define("COMMA", ",");
	define("HYPHEN", "-");
	define("SLASH", "/");
	define("ASTER", "*");
	define("DD", ":-:");    // DATA DELIMITER

	define("MOD_ORDER", 100);
	define("MOD_DATA", 010);
	define("MOD_STATE", 001);

?>
